### ISSUE TITLE
Cheetah Raspberry Pi OS Clarification

### ISSUE THREAD

**Issue by hankp46** [Picovoice/cheetah#11]
Just trying to clarify what OS open source Cheetah will run on.
Will it run on linux x86 OS or does it need an X86-64 environment or will it run on a raspian 64 bit OS?

And just an editorial opinion - it would be nice to have a open source version for us raspberry pi non-commercial enthusiasts (either 32 bit or 64 bit)

**Comment by kenarsa** [comment]
Its only x86-64. yeah, would be nice to do that but right now we don't have free offering running on arm. hopefully sometime in future when we figure how to enforce non-commercial use. thanks.
