### ISSUE TITLE
Adding Timestamps to Transcription

### ISSUE THREAD

**Issue by BilalMH** [Picovoice/cheetah#123]
Hi, I'm loving what you have with Cheetah on Android so far. However, my use case is requiring me to use timestamps with the transcript object. Is there any way that this is going to be added or will be added?

**Comment by mrrostam** [comment]
Hi @BilalMH, I'm glad you like it :) 

The good news is [Leopard](https://github.com/Picovoice/leopard) is going to output timestamps in the next version. However, there is no plan to add this feature to Cheetah for now. I hope this helps you.

**Comment by BilalMH** [comment]
Hi @mrrostam, ah. Leopard doesn't do real-time transcription on a streaming source though right?

**Comment by mrrostam** [comment]
That's true.

**Comment by mrrostam** [comment]
I don't think so, as it's not the priority at the moment, and to be honest, it doesn't make much sense for Cheetah to have timestamps. I am closing the issue, but feel free to send us an email (via [hello@picovoice.ai](hello@picovoice.ai)) and explain your use cases. If we find it helpful to other users, we can bring it to our product manager's attention to add it to the plan.
