### ISSUE TITLE
Syntax error in NodeJS demo

### ISSUE THREAD

**Issue by phunanon** [Picovoice/cheetah#141]
Hi, I just tried pulling this down and trying it and it appears in the last 24h a syntax error has been introduced.

https://github.com/Picovoice/cheetah/blob/f64739d349729a8ba64699f3be0fe05ae1ab1b9e/demo/nodejs/mic.js#L43-L44

**Comment by mrrostam** [comment]
Thank you for reporting the issue. It's fixed now.
