### ISSUE TITLE
Absolute path for model file - Expo/React Native

### ISSUE THREAD

**Issue by grutt** [Picovoice/cheetah#158]
**Is your feature request related to a problem? Please describe.**
I'm attempting to use Picovoice-cheetah with an existing Expo react native application. Unfortunately, expo does not have an easy way to bundle the file into the application's asset directory for android, instead opting for it's own [asset management lib](https://docs.expo.dev/versions/latest/sdk/asset/). AFIK the Cheetah.create method is relative to the /asset/ path only.

**Describe the solution you'd like**
I'd like to simply provide an absolute path to the file system. I.e.: 
`file:///data/user/0/app/cache/ExponentAsset-4e3f888fc8475f69fd5fa32f1ad5216a.pv`

**Describe alternatives you've considered**
I'm not going to eject my app for this. 

**Additional context**
The model is fairly large, supporting this feature would also allow the model to be shipped independently of the app reducing bundle sizes.

**Comment by laves** [comment]
@grutt - good news, the model path does not need to be relative to assets directory. That is purely for the convenience of the majority of the users. If you give it an absolute path to a `.pv` file on the device, it will use that and not search for it relative to the assets directory.

**Comment by grutt** [comment]
Thanks for the quick reply!

Hmmm, when I provide it the abs path with the file:// prefix it's returning
a java error for file not found. I've confirmed the file does indeed exist
at the uri.

I can create a stub app/repo but I'm on the run at the moment.

**Comment by grutt** [comment]
🤦 
Removing the protocol worked... sometimes it's the little things. 
Thank you for your help, might be a good idea to clarify the path docs to specify how the path is resolved.

**Comment by laves** [comment]
Great! Yes, agreed, we'll be updating the docs to be more specific.
