### ISSUE TITLE
python core dump

### ISSUE THREAD

**Issue by strohni** [Picovoice/cheetah#18]
The C demo runs but the python demo core dumps.  Details below, any ideas on how to debug?  Thanks.

root::system { /usr/local/cheetah-master }-> ./cheetah_demo ./lib/linux/x86_64/libpv_cheetah.so ./lib/common/acoustic_model.pv ./lib/common/language_model.pv ./resources/license/cheetah_eval_linux_public.lic ./resources/audio_samples/test.wav
 [WARN] this is an evaluation license. use of this software in a commercial product is strictly prohibited.
 [WARN] you may transcribe files that are shorter than '100' seconds.
 [WARN] your evaluation license will expire in 59 days
MISTER COULTER IS THE APOSTLE OF THE MIDDLE CLASSES AND WE'RE GLAD TO WELCOME HIS GOSPEL
root::system { /usr/local/cheetah-master }-> python3 demo/python/cheetah_demo.py --audio_paths resources/audio_samples/test.wav
 [WARN] this is an evaluation license. use of this software in a commercial product is strictly prohibited.
 [WARN] you may transcribe files that are shorter than '100' seconds.
 [WARN] your evaluation license will expire in 59 days
Segmentation fault (core dumped)
root::system { /usr/local/cheetah-master }-> python3 -V
Python 3.6.8
root::system { /usr/local/cheetah-master }-> cat /etc/centos-release 
CentOS Linux release 7.0.1406 (Core)

**Comment by kenarsa** [comment]
are you using CentOS Linux? The Python demo available here is only tested on Ubuntu. I suggest trying it out on Ubuntu. It is clearly an issue related to the Python version you are using.

**Comment by strohni** [comment]
Hi Alireza - The Python version is listed in the text; 3.6.8.  Your documentation says "The demo has been tested using Python 3.6".  Please advise what version I should be using.  Thank you.

**Comment by kenarsa** [comment]
the free version is built to run on Ubuntu. We don't support CentOS out of the box. Makes sense? the only way we might to it is via a commercial engagement. for that, if interested, please reach out via our website.

**Comment by strohni** [comment]
Yes, we're trying to establish some level of functionality before entering commercial agreement.  If only Ubuntu is supported, this line in your docs could use clarification: "Linux (x86_64) is available for non-commercial use free of charge.".  I will try the Ubuntu route, thank you.

**Comment by kenarsa** [comment]
that's a valid point. made the change.
