### ISSUE TITLE
Output from python, none from c

### ISSUE THREAD

**Issue by strohni** [Picovoice/cheetah#19]
On one of my machines, I get output from the python wrapper but none from calling the C lib directly using the same wav file as input. 

[nick@localhost cheetah-master]$ python3 demo/python/cheetah_demo.py --audio_paths /mnt/hgfs/Shared/2.wav 
 [WARN] this is an evaluation license. use of this software in a commercial product is strictly prohibited.
 [WARN] you may transcribe files that are shorter than '100' seconds.
 [WARN] your evaluation license will expire in 58 days
AM I DOING A DEMO WITH SOME REPRESENTATIVES FROM AT ME CORPORATION AND WERE JUST TESTING OUT THE VOICE FEATURES AND LOOKS SOMEWHAT RECORD THIS WAY OF FILE AND SENT IT OFF AND HAVE A GOOD DAY
[nick@localhost cheetah-master]$ ./cheetah_demo ./lib/linux/x86_64/libpv_cheetah.so ./lib/common/acoustic_model.pv ./lib/common/language_model.pv ./resources/license/cheetah_eval_linux_public.lic /mnt/hgfs/Shared/2.wav
 [WARN] this is an evaluation license. use of this software in a commercial product is strictly prohibited.
 [WARN] you may transcribe files that are shorter than '100' seconds.
 [WARN] your evaluation license will expire in 58 days

[nick@localhost cheetah-master]$

**Comment by kenarsa** [comment]
I hardly doubt this is an issue with the cheetah. if you want us to look into it you need to share the audio file you are using and we can try to reproduce.

**Comment by strohni** [comment]
I reproduced this on Ubuntu, wav file: https://drive.google.com/file/d/1pfKqEQR0OqiMgJCN8_bAX43XhzN9rP7S/view?usp=sharing

nick@ubuntu:~/cheetah-master$ python3 demo/python/cheetah_demo.py --audio_paths 2.wav
 [WARN] this is an evaluation license. use of this software in a commercial product is strictly prohibited.
 [WARN] you may transcribe files that are shorter than '100' seconds.
 [WARN] your evaluation license will expire in 58 days
AND YOU'RE DOING A DEMO WITH SOME REPRESENTATIVES FROM AT ME CORP AND WERE JUST TESTING OUT THE VOICE FEATURES AND LOOKS SOMEWHAT RECORD THIS WAY OF FILE AND SENT IT OFF AND HAVE A GOOD DAY
nick@ubuntu:~/cheetah-master$ ./cheetah_demo ./lib/linux/x86_64/libpv_cheetah.so ./lib/common/acoustic_model.pv ./lib/common/language_model.pv ./resources/license/cheetah_eval_linux_public.lic 2.wav 
 [WARN] this is an evaluation license. use of this software in a commercial product is strictly prohibited.
 [WARN] you may transcribe files that are shorter than '100' seconds.
 [WARN] your evaluation license will expire in 58 days

nick@ubuntu:~/cheetah-master$

**Comment by kenarsa** [comment]
https://github.com/Picovoice/cheetah#file-based-demo-1

the wav file has to be 16-bit. your file is a 32-bit float. see the note above and also pv_cheetah.h for more documentation, please.

**Comment by strohni** [comment]
OK thanks my mistake.  FYI the Python wrapper seems to work consistently with wavs recorded in the same format, somehow.

**Comment by kenarsa** [comment]
all good. python demo converts to 16-bit if a different format. c demo does not.
