### ISSUE TITLE
Cheetah (temporarily unavailable) ?

### ISSUE THREAD

**Issue by tempo-riz** [Picovoice/cheetah#193]
![image](https://github.com/Picovoice/picovoice/assets/64015162/02417683-c14a-4340-929a-087e80104faf)
Curently there seem to be some issue to download a cheetah model (any language) any update on this ?
While this is beeing fixed I can use the default model (english) here https://github.com/Picovoice/cheetah/tree/master/lib/common 
but are the source files for others language avalable somewhere ?
Thanks !

**Comment by kenarsa** [comment]
We know about this. Cheetah custom models are disabled to the public temporarily. I cannot tell you when it will be re-enabled. In the meantime, you can use the default or custom models with Leopard.

**Comment by tempo-riz** [comment]
Hello, any update ?
