### ISSUE TITLE
Cheetah + Eagle

### ISSUE THREAD

**Issue by josiahbryan** [Picovoice/cheetah#226]
**Is your feature request related to a problem? Please describe.**
I want to identify people speaking in live transcriptions. However, I can't find a way to correlate the output of Eagle (https://picovoice.ai/docs/api/eagle-web/) with the output of Cheetah because Cheetah is async (no correlation of output to the input frame), whereas Eagle gives one-to-one results correlated with input audio frame.

**Describe the solution you'd like**
Any way of making Eagle work with Cheetah.

Perhaps timestamps in Cheetah output so I can correlate the results myself, or direct integration of Eagle into Cheetah. Or at minimum, a specific awaitable sync API that I can use to process an audio frame, like Eagle has:

```
async function process(pcm: Int16Array): Promise<number[]>
```

Though for Cheetah, it could be:
```
async function process(pcm: Int16Array): Promise<string>
```

Even just THAT would be enough...can we get an async `process` call?

**Describe alternatives you've considered**
`whisper.cpp` 

**Additional context**
N/A

**Comment by kenarsa** [comment]
Unfortunately, no. You are correct. Cheetah is async. We are adding diarization to Leopard soon, but that won't give you live transcription.

**Comment by josiahbryan** [comment]
Understandable. But what about time stamps? Can you at least it so it provides time stamps for the transcription? Then we could correlate it reliably with eagle?
