### ISSUE TITLE
Raspberry pi won’t run run the python real-time demo

### ISSUE THREAD

**Issue by Lowe231** [Picovoice/cheetah#23]
I downloaded the entire cheetah folder on my raspberry pi zero w but the code will not run. When I tried using the “python” command the terminal would spit back that the was a syntax error on line 67 with end=‘’.

**Comment by kenarsa** [comment]
https://github.com/Picovoice/cheetah#license

**Comment by Lowe231** [comment]
I don’t understand what you are trying to tell me
