### ISSUE TITLE
Cheetah Issue: pvcheetah._cheetah.CheetahActivationError

### ISSUE THREAD

**Issue by catdogmat** [Picovoice/cheetah#230]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour

Starts Fine

### Actual behaviour

Errors with pvcheetah._cheetah.CheetahActivationError

### Steps to reproduce the behaviour

Enter startup code
Run program
Error Appears
(Include enough details so that the issue can be reproduced independently.)

**Comment by mrrostam** [comment]
It seems that there is some issue with our license manager. Do you have internet connectivity? If yes, are you using some sort of firewall?

**Comment by catdogmat** [comment]
Yes, I'm using Fortinet's Firewall/Blocking.

**Comment by mrrostam** [comment]
You probably need to whitelist `*.picovoice.net` to ensure that our license manager can establish a connection with our servers.
