### ISSUE TITLE
License file from the repo is not working

### ISSUE THREAD

**Issue by parveezms** [Picovoice/cheetah#24]
ubuntu@ip-172-31-12-249:~/cheetah-master$ python3.6 demo/python/cheetah_demo.py --audio_paths resources/audio_samples/test.wav
 [WARN] this is an evaluation license. use of this software in a commercial product is strictly prohibited.
 [WARN] you may transcribe files that are shorter than '100' seconds.
 [WARN] your evaluation license has expired
Traceback (most recent call last):
  File "demo/python/cheetah_demo.py", line 55, in <module>
    license_path=args.license_path)
  File "demo/python/../../binding/python/cheetah.py", line 80, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]('Initialization failed')
ValueError: Initialization failed

**Comment by kenarsa** [comment]
updated. please try again.
