### ISSUE TITLE
Cheetah Issue: Where is the model for Italian?

### ISSUE THREAD

**Issue by StefanoGiu** [Picovoice/cheetah#241]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
Recognize italian voice

### Actual behaviour
Only English is working

### Steps to reproduce the behaviour

(Include enough details so that the issue can be reproduced independently.)

Where is the model for Italian?

**Comment by kenarsa** [comment]
Cheetah is English-only at this time.
