### ISSUE TITLE
Cheetah Issue: Not able to run react-native demo

### ISSUE THREAD

**Issue by yuriigeivakh** [Picovoice/cheetah#242]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Steps to reproduce the behaviour

(Include enough details so that the issue can be reproduced independently.)

Error in the build

2023-09-23 12:06:04.123 xcodebuild[24268:226505] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
** BUILD FAILED **

The following build commands failed:
        CompileC /Users/macbook/Library/Developer/Xcode/DerivedData/CheetahDemo-fwhygzowyhfrkdeoexlgofvvlwxx/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Yoga.build/Objects-normal/x86_64/Yoga.o /Users/macbook/Desktop/🎸/cheetah/demo/react-native/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'Yoga' from project 'Pods')
(1 failure)

**Comment by ErisMik** [comment]
Hi, thanks for the report. Looks like it's a versioning issue between XCode and react-native. There's a [PR](https://github.com/Picovoice/cheetah/pull/243) with a fix for the demo in the repository incoming but you can solve it in your project/demo by upgrading the `react-native` package in your `package.json` from `0.68.5` -> `0.68.7` as seen [here](https://github.com/Picovoice/cheetah/pull/243/files#diff-fdec3ffd5f2ed32370a34c02c8fec3f8b243f4590c1d9bcae39816c3aef3c773R23).

**Comment by kenarsa** [comment]
@yuriigeivakh I think the PR is in and should have resolved your issue. If not, please reopen as needed.
