### ISSUE TITLE
[ERROR] license file has incorrect format

### ISSUE THREAD

**Issue by srigandeswaran** [Picovoice/cheetah#25]
I tried to run the picovoice Realtime demo file in my system with the updated license,but it ended up with showing error as
[ERROR] license file has incorrect format
Could you please help me out to resolve this issue?

Thanks in advance.

**Comment by kenarsa** [comment]
whats the OS and CPU?

**Comment by vandana4** [comment]
I am getting same error, I am trying on Ubuntu 14.04 x86_64

**Comment by srigandeswaran** [comment]
Iam using ubuntu 14.04 LTS x86-64 ,INTEL core i3 and linux kernel version 4.4.0-121-generic

**Comment by kenarsa** [comment]
We've tested cheetah on 16.04 and 18.04. I doubt this is the problem though. clone a clean repo and try again. I just tested it and it works on my box.
