### ISSUE TITLE
Raspberry pi 5 Support

### ISSUE THREAD

**Issue by EthanOscarson** [Picovoice/cheetah#253]
Hey there,

I'm looking to use picovoice with my new raspberry pi 5 - is it supported?

Docs only reference 3, 4, and 400, so if it is supported an update to the docs would be great!

**Comment by ErisMik** [comment]
Hi, official Raspberry Pi 5 support is coming but is unfortunately not available at the moment. I will keep this issue open and comment+close once that support is released.

In the meantime, you may be able to try and see if one of the other Raspberry Pi libraries [will work](https://github.com/Picovoice/rhino/issues/583), but there are no guarantees and it won't be properly optimized.

**Comment by ErisMik** [comment]
Tracked by https://github.com/Picovoice/picovoice/issues/721 instead.
