### ISSUE TITLE
Realtime demo not working.

### ISSUE THREAD

**Issue by karayakar** [Picovoice/cheetah#26]
I am getting error ;

python demo/python/cheetah_demo_realtime.py --library_path lib/linux/x86_64/libpv_cheetah.so --acoustic_model_path lib/common/acoustic_model.pv --language_model_path lib/common/language_model.pv --license_path resources/license/cheetah_eval_linux_public.lic
LoadLibrary() argument 1 must be str, not None

**Comment by kenarsa** [comment]
whats the platform?

**Comment by karayakar** [comment]
Windows.

**Comment by karayakar** [comment]
windows 10 pro.

**Comment by kenarsa** [comment]
read the docs. the free demo only runs on ubuntu x86_64

https://github.com/Picovoice/cheetah#license
