### ISSUE TITLE
Request to extend to other operating systems

### ISSUE THREAD

**Issue by nuttyartist** [Picovoice/cheetah#27]
I'm developing a program to help people control their computers using their voice called Deus: https://www.deus-ai.com. [Github link](https://github.com/nuttyartist/deus). Deus is open-source and free.

I'm currently using Google's Speech-to-text engine but I'd really like to use Cheetah since it's running offline. That will help with security and privacy but not merely since with enough users I won't be able to afford Google's billing all by myself. But currently, only Linux is supported for non-commercial use with Cheetah. Deus is a cross-platform application and I'd like it to stay that way. Can you help me by making Cheetah supported on Mac and Windows also?

Your technologies are incredibly impressive and I think Deus will be an interesting way to show them off.

**Comment by mehrdadfeller** [comment]
Currently, we are focused on servicing mid to large scale enterprise clients. The sole purpose of the code we have published on GitHub is to allow our customers to freely evaluate the performance and ease-of-integration before signing up for added paid services and development tools. 

Also, please note that the evaluation version of Cheetah is NOT "Apache 2.0" and is time-bombed to prevent usage in the production environment.  For more information please read the license:

https://github.com/Picovoice/cheetah/blob/master/LICENSE

**Comment by nuttyartist** [comment]
I think you should make it more clear in your README that your project is on Github solely for the evaluation for commercial clients. Otherwise, people like me can think they found a cool free to use software to integrate into their free and open source apps. Thanks.
