### ISSUE TITLE
[Error] License file has incorrect format

### ISSUE THREAD

**Issue by hikaru-coder** [Picovoice/cheetah#28]
Hi Sir,

I am using Ubuntu 14.04 LTS to try your demo. I had complied using gcc -I include/ -O3 demo/c/cheetah_demo.c -ldl -o cheetah_demo -std=c99. However, I faced problem when I tried to run the following:
./cheetah_demo \
./lib/linux/x86_64/libpv_cheetah.so \
./lib/common/acoustic_model.pv \
./lib/common/language_model.pv \
./resources/license/cheetah_eval_linux_public.lic \
./resources/audio_samples/test.wav

It gave me an error of the following:

[Error] license file has incorrect format

Is there anyway to resolve this? Is it due to Ubuntu 14.04 LTS? Does it need a specific compiler?

**Comment by kenarsa** [comment]
on Ubuntu 18.04 this runs correctly. Is this an x86_64 machine?

**Comment by kenarsa** [comment]
on Ubuntu 18.04 this runs correctly. Is this an x86_64 machine?

**Comment by hikaru-coder** [comment]
Yes. It is an x86_64 machine. Does it only support Ubuntu 18.04?

**Comment by kenarsa** [comment]
We haven't tested it on 14.04 but on 16.04 and 18.04 it works. suggest upgrading OS.

**Comment by stefan-reich** [comment]
I have the same problem with Peppermint 7. Granted it's an old distro.
