### ISSUE TITLE
Timeline for french ?

### ISSUE THREAD

**Issue by tempo-riz** [Picovoice/cheetah#286]
Hello I noticed you enabled custom model training for Cheetah, great work !

Are you planning to add support for french any soon ? 
Would be awesome if you could provide a timeline.

![image](https://github.com/Picovoice/cheetah/assets/64015162/4998b55c-d5ff-4a65-a691-614eca4d0fc6)

**Comment by kenarsa** [comment]
I don't have a timeline, sorry.
