### ISSUE TITLE
Finding out audio device name

### ISSUE THREAD

**Issue by stefan-reich** [Picovoice/cheetah#29]
Hi,

I'm not sure how to get the audio device name for the realtime demo. This is on Peppermint Linux 10:

```
$ arecord -L
null
    Discard all samples (playback) or generate zero samples (capture)
pulse
    PulseAudio Sound Server
default
    Playback/recording through the PulseAudio sound server
sysdefault:CARD=Generic_1
    HD-Audio Generic, ALC236 Analog
    Default Audio Device
front:CARD=Generic_1,DEV=0
    HD-Audio Generic, ALC236 Analog
    Front speakers
dmix:CARD=Generic_1,DEV=0
    HD-Audio Generic, ALC236 Analog
    Direct sample mixing device
dsnoop:CARD=Generic_1,DEV=0
    HD-Audio Generic, ALC236 Analog
    Direct sample snooping device
hw:CARD=Generic_1,DEV=0
    HD-Audio Generic, ALC236 Analog
    Direct hardware device without any conversions
plughw:CARD=Generic_1,DEV=0
    HD-Audio Generic, ALC236 Analog
    Hardware device with all software conversions
```

Where in this output is the AUDIO_DEVICE_NAME I have to use?

Thanks

**Comment by stefan-reich** [comment]
With some values I get this error:

```
./cheetah_demo_realtime lib/linux/x86_64/libpv_cheetah.so sysdefault:CARD=Generic_1 lib/common/acoustic_model.pv lib/common/language_model.pv resources/license/cheetah_eval_linux_public.lic
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
'snd_pcm_open' failed with 'Device or resource busy'
```

I thought with ALSA multiple applications can record at once? Has never been a problem.

**Comment by kenarsa** [comment]
try to record something using arecord and then use the same device for demo closing for now as this is not a cheetah issue. if you managed to record using arecord but couldn't use the same device for running the demo please reopen and we can take a look.

**Comment by stefan-reich** [comment]
My apologies. Yes it was an ALSA/PulseAudio problem - I had to close the volume control application (pavucontrol) in order for this to work. Not sure why dsnoop doesn't allow concurrent access (I thought it would). Thanks.

**Comment by stefan-reich** [comment]
I understand why you say it's not a cheetah issue... but it actually is. We are supposed to use the executable, right? Right nowthere is a problem. Also, couldn't the default audio device just be used?

Many greetings
