### ISSUE TITLE
Picovoice Documentation Issue (/docs/quick-start/cheetah-python/)

### ISSUE THREAD

**Issue by rohitkuyadav** [Picovoice/cheetah#294]
Hey! I'm currently facing issues with creating a speech-to-text program pvcheetah Python package.
Can you please provide me the sample of code for the same

**Comment by mrrostam** [comment]
We have a [quick-start](https://picovoice.ai/docs/quick-start/cheetah-python/) page in our documentation that assists you in taking the initial steps. It includes links to some demos as well.
