### ISSUE TITLE
Cheetah Issue: Flutter iOS Demo app has some slight problems

### ISSUE THREAD

**Issue by timmolter** [Picovoice/cheetah#297]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Cheetah docs
- [X] I have searched the existing issues for Cheetah

### SDK

Flutter

### Cheetah package version

2.0.0

### Framework version

Flutter 3.16.8

### Platform

iOS

### OS/Browser version

macOS 14.2.1

### Describe the bug

While I did manage to get the Cheetah Flutter demo app working on iOS, I wanted to note some minor issues:
1. running `flutter run --release` works, but `flutter run` does not work. The app loads on the phone and then crashes.
2. There's an error in the console: `[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.`
3. There are a lot of warnings in XCode. See attached screenshots.

<img width="578" alt="Screenshot 2024-01-18 at 12 31 28 PM" src="https://github.com/Picovoice/cheetah/assets/738972/831a37a3-9f40-451b-9ba7-db8e3c39555c">
<img width="576" alt="Screenshot 2024-01-18 at 2 28 22 PM" src="https://github.com/Picovoice/cheetah/assets/738972/9cd9a448-bd2f-4e45-8404-5b78e856e556">

### Steps To Reproduce

1. Fresh clone of the cheetah repo.
2. run `flutter run`

### Expected Behavior

I would expect `flutter run` to work. It does work for the demo flutter app in <https://github.com/Picovoice/flutter-voice-processor>.
There should be no errors and ideally no warnings. Perhaps someone with knowhow needs to freshen up the iOS demo app a bit.

**Comment by laves** [comment]
Thanks for reporting - we'll take a look

**Comment by laves** [comment]
@timmolter - I tried `flutter run` as you said and it worked for me. The warnings and console error that you've indicated don't seem related to Cheetah, but it is possible. What XCode version are you running?

**Comment by laves** [comment]
Closed due to inactivity
