### ISSUE TITLE
Failed to process with 'INVALID_STATE'

### ISSUE THREAD

**Issue by stefan-reich** [Picovoice/cheetah#31]
cheetah_demo_realtime on Linux. The first 4 lines are (somewhat) recognized lines. Then the error, which occurs sporadically:

```
GO
DOWN LIKE A
DOWN LIKE A
DOWN AND LOOKED UP
failed to process with 'INVALID_STATE'.

```
I could just restart the process if that happens, but... let's say it's ugly.

BTW we are very likely buying this

**Comment by kenarsa** [comment]
for all commercial inquiries reach out to this: https://picovoice.ai/contact
please use Github only for technical issues. I would like to be able to reproduce this issue so the team can work on it. on my ubuntu 18.04 desktop, I can't. please provide more information about your machine and setup. we will address the issue if we can reproduce it internally.

**Comment by kenarsa** [comment]
closed due to inactivity. reopen if needed

**Comment by stefan-reich** [comment]
Hi, the issue is still happening quite frequently. I am using a Peppermint Linux 10 (64 Bit) on a Ryzen 5 notebook. Anything else I can do to debug? Would love to help.

**Comment by kenarsa** [comment]
If you give me step-by-step directions to reproduce on Ubuntu 18.04, I can take a look.

**Comment by stefan-reich** [comment]
OK I have just upgraded Cheetah to latest version from GitHub (am yet to see the bug again since that). Just in case I am setting up a virtual Ubuntu 18.04 to replicate it there.

**Comment by stefan-reich** [comment]
Bug still happens. In a naked Ubuntu 18.04 (64 Bit), I basically do:

  sudo usermod -a -G audio stefan
  reboot
  sudo apt install git gcc libasound2-dev
  git clone https://github.com/Picovoice/cheetah.git
  cd cheetah
  gcc -I include/ -O3 demo/c/cheetah_demo_realtime.c -ldl -lasound -o cheetah_demo_realtime
  ./cheetah_demo_realtime lib/linux/x86_64/libpv_cheetah.so sysdefault:CARD=I82801AAICH lib/common/acoustic_model.pv lib/common/language_model.pv resources/license/cheetah_eval_linux_public.lic

...and after a while, the error message appears.

**Comment by kenarsa** [comment]
OK. I think I know what this is. You reached the 100 second transcription limit for the evaluation license. The engine prints it out in the console upon execution. Right?

I will add explicit message and also add it to README.md
