### ISSUE TITLE
Cheetah feature : keyword spotting

### ISSUE THREAD

**Issue by tempo-riz** [Picovoice/cheetah#312]
Hello, I don't know what's the best place to ask about this but here I am,
When using custom keywords/boosting feature it would be amazing to have them in the result of the process.

These are the current data model returned by cheetah (in dart but I guess it looks similar on others platforms) :
```
class CheetahTranscript {
  final String? _transcript;
  final bool? _isEndpoint;
  final List<String> keywordsFoundInTranscript;   <---------- add something like this
}
```

I dont know if this is possible based on how cheetah works but if it is it would be really handy (instead of interating over the transcript afterwards).
Thanks

**Comment by ErisMik** [comment]
Sorry for the late reply. This feature doesn't make sense to implement in Cheetah itself, it is too application specific. In any case, Cheetah would essentially just be iterating over the transcript afterwards regardless.
