### ISSUE TITLE
Question on custom keywords/boost

### ISSUE THREAD

**Issue by tempo-riz** [Picovoice/cheetah#316]
![Untitled (1)](https://github.com/Picovoice/cheetah/assets/64015162/f7680c3c-9f00-4967-ba9c-e201a97a2563)

Here what is the behavior ?

we can see that "a fire ball" and "a-fire-ball" have the same IPA, does it changes something else ? Like the speed of prononciation or other, not an expect on the topic :')
I would prefer to use the one with dashes - in all my custom that contains spaces is that okay or a bad practice ? 

I tested adding them  and boosting them (not at the same time) to see the difference but it seems inconsistent...

**Comment by laves** [comment]
@tempo-riz, your observations are correct. We treat "a fire ball" exactly the same as "a-fire-ball" - there is no difference in expectations of how it will be pronounced. If you would like one to be differentiated, you can change the custom pronunciation, but other than that it would come down to which word makes the most sense in the context of the surrounding speech.

**Comment by tempo-riz** [comment]
So juste to be sure even if i add "a-fire-ball" the model output will probably be "a fire ball" right ? Because that would make more sense in common speech I guess

**Comment by laves** [comment]
Yes, that's correct. In this case it would not be beneficial to have both unless you set two different pronunciations.
