### ISSUE TITLE
Question: Grammar support

### ISSUE THREAD

**Issue by reinzor** [Picovoice/cheetah#32]
Can `cheetah` be used for closed-world grammar speech recognition (like https://docs.microsoft.com/en-us/dotnet/api/system.speech.recognition.grammar?view=netframework-4.8) ? If not, could you provide some pointers on how we could implement this?

**Comment by kenarsa** [comment]
you should check this: https://github.com/Picovoice/rhino

**Comment by reinzor** [comment]
Thanks!
