### ISSUE TITLE
Picovoice Console Issue:  Default Cheetah model

### ISSUE THREAD

**Issue by Duraggman** [Picovoice/cheetah#322]
Sorry if this is silly. I'm trying to use PicoVoice Cheetah for a real-time conversation monitor, which is my uni project and I wanted to use the default model since a custom one isn't required but I don't know where to find it. Sorry again if I've misread the docs.

**Comment by ErisMik** [comment]
https://github.com/Picovoice/cheetah/tree/master/lib/common
