### ISSUE TITLE
Trying to get in contact with you!

### ISSUE THREAD

**Issue by LarsJanssenTUe** [Picovoice/cheetah#33]
Over the last few weeks we, as Tech United (https://github.com/tue-robotics, https://www.techunited.nl/), have been trying to get into contact with you through both your online contact form and your emailadress (hello@picovoice.ai), however so far we have not been able to. Could you help us out by directing us in the correct direction?

**Comment by kenarsa** [comment]
Happy to help out with bugs/tech questions here.

Regarding email/contact form: the business team might not get back to you if (1) there are missing information (2) the commercial opportunity is not a good match.
