### ISSUE TITLE
Need help: Cheetah audio sampling rate

### ISSUE THREAD

**Issue by pankajidwallet** [Picovoice/cheetah#332]
### What is the URL of the doc?

https://picovoice.ai/docs/api/cheetah-c/

### What is the nature of the issue?

Hello,
The current audio sampling rate of Cheetah seems to be 16kHz. I am getting a PCM stream at 32kHz (cannot change it). Is there any way in Cheetah to use a sampling rate of 32kHz...

**Comment by albho** [comment]
@pankajidwallet - Unfortunately no, PCM passed to Cheetah must have a sample rate of 16 kHz.

**Comment by pankajidwallet** [comment]
Ok, thanks for the prompt response though !
