### ISSUE TITLE
How are the limits on the free plan being monitored, and how does it affect our privacy?

### ISSUE THREAD

**Issue by MakingMadness** [Picovoice/cheetah#333]
### What is the URL of the doc?

https://picovoice.ai/pricing/

### What is the nature of the issue?

> Up to 5 hours/month
> Leopard Speech-to-Text
> Cheetah Streaming Speech-to-Text
> Koala Noise Suppression
> Eagle Speaker Recognition
> Falcon Speaker Diarization
> Octopus Speech-to-Index

How are these limits being monitored? Are you sending metadata home about our usage of Picovoice? If so, specifically what data and where in the source code can the transmission be reviewed? 5 hours doesn't seem like much, but the next tier is $500/m which is incredibly prohibitive for a personal project. Nervous to even start putting energy into this because of these concerns.

**Comment by kenarsa** [comment]
The [FAQ](https://picovoice.ai/pricing/) should answer some of your questions. The `Developer Plan` is definitely meant for enterprises and is expensive for individual developers ...

**Comment by MakingMadness** [comment]
When asking for transparency, I find it rather shady to get a vague and uncooperative answer.
