### ISSUE TITLE
frame length in cheetah

### ISSUE THREAD

**Issue by yuvalBGU1** [Picovoice/cheetah#341]
Hey, is there an option to change the  frame length of the recorder?
The frame length is too small and creates some buffer underflow waiting to process a large number of frames, i want to increace the size of each frame on order to combat some of the the cumulative delay.
Thank you!

**Comment by albho** [comment]
Unfortunately no, Cheetah only accepts a fixed frame length.

Since you mention "recorder" - are you possibly referring to [pvrecorder](https://github.com/Picovoice/pvrecorder) instead?

**Comment by yuvalBGU1** [comment]
yes, i am using PvRecorder(frame_length=cheetah.frame_length, device_index=args.audio_device_index)

**Comment by albho** [comment]
That's the correct usage - so unfortunately no, when used with cheetah the frame length must be set to Cheetah's frame length as you have done.
