### ISSUE TITLE
Wrong ELF class

### ISSUE THREAD

**Issue by man4567890** [Picovoice/cheetah#36]
Hi
Could you give me some pointers in what I'm doing wrong please
pi@controller-4004298892:~/cheetah $ python -V
Python 3.6.8
pi@controller-4004298892:~/cheetah $ python demo/python/cheetah_demo.py --audio_paths resources/audio_samples/test.wav --license_path /home/pi/cheetah/cheetah_eval_linux_expires_july_9th_2020.lic
Traceback (most recent call last):
  File "demo/python/cheetah_demo.py", line 61, in <module>
    license_path=args.license_path)
  File "demo/python/../../binding/python/cheetah.py", line 68, in __init__
    library = cdll.LoadLibrary(library_path)
  File "/usr/local/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: demo/python/../../lib/linux/x86_64/libpv_cheetah.so: wrong ELF class: ELFCLASS64
pi@controller-4004298892:~/cheetah $ which python
/usr/bin/python
pi@controller-4004298892:~/cheetah $

**Comment by kenarsa** [comment]
whats the os/machine?

**Comment by man4567890** [comment]
Hi
Raspberry Pi 3B+ with Stretch
Thanks

**Comment by kenarsa** [comment]
read the docs: https://github.com/Picovoice/cheetah#cheetah

what's available in this repo only works on x86_64 ubuntu. other platforms are only available to enterprises who acquired commercial license.

**Comment by man4567890** [comment]
So sorry for the inconvience caused, I did not see that
