### ISSUE TITLE
Alsa C Library for macOS?

### ISSUE THREAD

**Issue by DennisFaucher** [Picovoice/cheetah#37]
The live mic C examples fails on compile. Where does one obtain alsa/asoundlib.h for macOS? TIA

cd cheetah/
gcc -I include/ -O3 demo/c/cheetah_demo_realtime.c -ldl -lasound -o cheetah_demo_realtime
demo/c/cheetah_demo_realtime.c:12:10: fatal error: 'alsa/asoundlib.h' file not found
#include <alsa/asoundlib.h>
         ^~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by mehrdadfeller** [comment]
As explained on the README file, Cheetah is only available on Linux x86 for free evaluation. Mac OS version is only available under commercial development or distribution license. If this is for a non-personal application/product, feel free to reach out to our sales team through the contact form on our website:  https://picovoice.ai/contact/

**Comment by DennisFaucher** [comment]
@mehrdadfeller Thank you. Moved on to an Ubuntu install
