### ISSUE TITLE
Can the output be normal case, rather than all uppercase?

### ISSUE THREAD

**Issue by bret152** [Picovoice/cheetah#41]
I noticed in your demo video, and when I set up cheetah and tried it, that the output is in ALL CAPS.

I am looking for a solution that would give me speech to text for document creation purposes. ALL CAPS is not useful as it would have to be processed to put it in to normal casing.  

Is there an option to make cheetah output the text with normal casing and capitalization?

**Comment by Thierryonre** [comment]
Once you've got the transcript from Cheetah, you can capitalise the text yourself using python.

Maybe you could use:
`"\n".join([sentence.capitalize() for sentence in transcript.split("\n")])`

**Comment by kenarsa** [comment]
The current version gives out case-insensitive output. You can give it some style using comment above if you like.
