### ISSUE TITLE
Can I use cheetah in window 10 without  registering the company name

### ISSUE THREAD

**Issue by Tejask1** [Picovoice/cheetah#42]
I want to use cheetah for educational purpose but it want company name and email . Can I use it without providing company name or email.

**Comment by Thierryonre** [comment]
To get your license for non-commercial use, you can acquire it [here](https://console.picovoice.ai/), press personal console, login using your Github account, press PicoX at the top and then proceed to get your license.

**Comment by Tejask1** [comment]
@Thierryonre  i want  to use it in  windows 10 but it  ask company name and website to get licence for windows 10  but I am not working in any company so is there any other way of doing it

**Comment by kenarsa** [comment]
@Tejask1 We only offer the Linux version for personal use. This, I hope, changes in the future (mid-2021). Thanks!

**Comment by Tejask1** [comment]
@kenarsa  thanks for answer
