### ISSUE TITLE
License cross-platform question

### ISSUE THREAD

**Issue by gigawatts** [Picovoice/cheetah#43]
I just generated a Linux x86_64 cheetah license, but would now like to try the Windows or Raspberry Pi version.

Two questions:
1) Can I use the Linux x86_64 license on Windows, or an ARM powered Raspberry Pi?
2) If not, since I have a limit of 1 license, can I "expire" the one I have so I can generate one that will work on Windows or a Pi?

**Comment by kenarsa** [comment]
The library here only runs on Linux-based x86_64. That being said, the new version of Cheetah would give access to all platforms (including the ones you mentioned) to all personal users. Please stay tuned. closing for now.
