### ISSUE TITLE
stream audio from standard in pipe?

### ISSUE THREAD

**Issue by gigawatts** [Picovoice/cheetah#44]
Is it possible to use the cheetah python real time demo with an audio source from a standard in pipe, or from a FIFO buffer file, so that I can, for example, stream an audio source from somewhere else (like a microphone on another PC, over the network)?

**Comment by kenarsa** [comment]
You should be able to do this using the library. You need to do some plumbing yourself though. The process method access audio in chunks so it can come from anywhere really. 

https://github.com/Picovoice/cheetah/blob/master/include/pv_cheetah.h#L77

**Comment by gigawatts** [comment]
Meaning, the library supports it, but the python demo currently does not offer an audio device / pipe selection method?

**Comment by kenarsa** [comment]
correct
