### ISSUE TITLE
Windows vs Linux Performance

### ISSUE THREAD

**Issue by tanhejiang** [Picovoice/cheetah#46]
Hi, Can I know more about the difference in performance for running Cheetah on Linux v.s Windows? (if any). Currently, I will like to demo Cheetah on windows but it is only available on Linux.

**Comment by Zemaaan** [comment]
I have the same problem. Can't seem to download obtain a license file for Windows 10. Additionaly, Cheetah library is outdated, and only works on Python 2.

**Comment by kenarsa** [comment]
accuracy is exactly the same. Stay tuned for the new release of cheetah with major improvements and feature in coming months.
