### ISSUE TITLE
Rhino on Cheetah?

### ISSUE THREAD

**Issue by tanhejiang** [Picovoice/cheetah#47]
Can I use Cheetah as the input for Rhino to derive its Intent?

**Comment by kenarsa** [comment]
no. Rhino is end-to-end. It gets speech and gives out intent.

**Comment by thilojaeggi** [comment]
Wouldn't this be useful though, if Rhino doesn't recognize what has been said/can't associate it with an intent you can further process the text with for example Wolfram Alpha?
