### ISSUE TITLE
No output after running as described

### ISSUE THREAD

**Issue by clearhat** [Picovoice/cheetah#5]
When I run 

```
./cheetah_demo ./lib/linux/x86_64/libpv_cheetah.so ./lib/common/acoustic_model.pv ./lib/common/language_model.pv \
./resources/license/cheetah_eval_linux_public.lic ./resources/mywavefile.wav
```

I get:

```
 [WARN] this is an evaluation license. use of this software in a commercial product is strictly prohibited
 [WARN] your evaluation license will expire in 74 days
```

Thereafter, nothing happens. What am I missing?

**Comment by clearhat** [comment]
Found it!

Missed the line in documentation that said the file had to be 16khz. I ran the following line on my file to convert it, and everything worked:

`ffmpeg -i mywavefile.wav -acodec pcm_s16le -ac 1 -ar 16000 mywavefile_16khz.wav`

**Comment by kenarsa** [comment]
cool. closing.
