### ISSUE TITLE
Customize cheetah STT engine to understand specific terms.

### ISSUE THREAD

**Issue by rushitbhadaniya** [Picovoice/cheetah#51]
I am currently testing the cheetah speech-to-text engine on my pc. The accuracy of the speech-to-text conversion is not coming so satisfying. It's not recognizing some specific words and some industry-specific terms. So, How can we train it to understand specialized terms?

**Comment by kenarsa** [comment]
Not available at the moment but soon. can't commit to a timeline at this time. Stay tuned!
