### ISSUE TITLE
Raspberry pi unable to setup

### ISSUE THREAD

**Issue by JustTheLogan** [Picovoice/cheetah#53]
So I have been trying to get this to work without success. 

I am trying to get this to work on the raspberry pi 4. does anyone have any idea on how to achieve this? i'm rather new to the linux system. 

I can install the list of requirements but past that, no idea on what i'm doing wrong. 
else, is there a tutorial somewhere? I really don't want to use the googleAPI..

there is plenty of information on the website and on github but for people who are still new like me, the struggle is real. 

to get an idea on what im trying to achieve:
use Picovoice Cheetah to directly convert speech to text
use Picovoice Porcupine for custom word trigger. 

any help would be much appreciated

-Logan

**Comment by kenarsa** [comment]
can you please clone a new repo and try again? this should solve your problem.
