### ISSUE TITLE
Issue with realtime_issue.py

### ISSUE THREAD

**Issue by Technerder** [Picovoice/cheetah#6]
The program prints this out when it is run:

`tech@laptop:~/Cheetah/demo/python$ sudo python3 realtime_demo.py 
 [WARN] this is an evaluation license. use of this software in a commercial product is strictly prohibited
 [WARN] your evaluation license will expire in 59 days
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
Listening... use SIGINT (ctrl+C) to stop listening and transcibe.
`

Yet nothing is being recognised or printed. Run on Debian 9.6

**Comment by kenarsa** [comment]
Are you sure that your mic is working?

**Comment by Technerder** [comment]
I believe so. All other applications which are reliant on my microphone seem to be working perfectly.

**Comment by kenarsa** [comment]
interesting. if you record yourself and use the offline demo would it work?

**Comment by Technerder** [comment]
I attempted to use an mp3 file to test this and a RunTime error was thrown:
`tech@laptop:~/Cheetah/demo/python$ sudo python3 cheetah_demo.py --audio_paths  /home/tech/Cheetah/Test.mp3
 [WARN] this is an evaluation license. use of this software in a commercial product is strictly prohibited
 [WARN] your evaluation license will expire in 56 days
Traceback (most recent call last):
  File "cheetah_demo.py", line 70, in <module>
    audio, sample_rate = soundfile.read(audio_path, dtype='int16')
  File "/usr/local/lib/python3.5/dist-packages/soundfile.py", line 257, in read
    subtype, endian, format, closefd) as f:
  File "/usr/local/lib/python3.5/dist-packages/soundfile.py", line 627, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/usr/local/lib/python3.5/dist-packages/soundfile.py", line 1182, in _open
    "Error opening {0!r}: ".format(self.name))
  File "/usr/local/lib/python3.5/dist-packages/soundfile.py", line 1355, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening '/home/tech/Cheetah/Test.mp3': File contains data in an unknown format.
`

**Comment by kenarsa** [comment]
you need to use a WAV file.

**Comment by Technerder** [comment]
Ah, my bad. It works perfectly when using a wav file.

**Comment by Technerder** [comment]
However the realtime_demo still prints out those errors. But now it seems to print out what is has detected after I use 'Ctrl + C' to interrupt the program.

**Comment by Technerder** [comment]
I've just read over the method here (https://github.com/Picovoice/cheetah/blob/master/demo/python/realtime_demo.py#L81) which explains why it only prints out the result after I interrupt the program, but I'm not quite sure why it is written like this and doesn't just dynamically print out the result? Is there a reason for this?

**Comment by kenarsa** [comment]
The engine does not provide online decoding currently. We are planning to add it at a later point in time.
