### ISSUE TITLE
Demo Issue: Failed to load libpv_cheetah.so

### ISSUE THREAD

**Issue by nafanwin** [Picovoice/cheetah#7]
On macOS Mojave 10.14.3, I tried running the following from the demo after cloning the repo:

`gcc -I include/ -O3 demo/c/cheetah_demo.c -ldl -o cheetah_demo`

`./cheetah_demo ./lib/linux/x86_64/libpv_cheetah.so ./lib/common/acoustic_model.pv ./lib/common/language_model.pv ./resources/license/cheetah_eval_linux_public.lic ./resources/audio_samples/test.wav`

I recieved this error message:
`[ERROR] Failed to load Cheetah's library at './lib/linux/x86_64/libpv_cheetah.so'.`

The file exists (and I assume compilation was successful), so I'm not sure what I did wrong. Thanks in advance for your help!

**Comment by kenarsa** [comment]
Yeah. The library here only works on Ubuntu.

https://github.com/Picovoice/cheetah#license
