### ISSUE TITLE
Recognizing Polish language in Cheetah speech-to-text

### ISSUE THREAD

**Issue by dastin-sandura** [Picovoice/cheetah#91]
Hi Picovoice team!

I am working on my Computer Science Master's Thesis, which is a mobile application for tracking the progress of your goals using the voice interface. I will be performing studies, which will compare user engagement with and without user interface to determine if voice control is something that increases the productivity and engagement of users.

I have searched through available solutions for Flutter and there is no other voice recognition solution as good as Picovoice! 😄 
In terms of API, reliability, and latency it is unmatched.

MVP is aimed primarily at the Polish market, which leads to my question: how can support for the Polish language be added?
Currently, the app has the most emphasis on continuous voice-to-text, which is why I am asking about Cheetah.

Hope to hear from you.

Best,
Dastin  Sandura

**Comment by kenarsa** [comment]
Thank you @dastin-sandura! Right now we only support English. I am sure we add new languages but I don't have a timeline for you, unfortunately.
